### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gamegam** [FoxWorn3365/Shopkeepers#1]
[13:18:09.458] [Server thread/EMERGENCY]: Crash occurred while handling a packet from session: plug Plugins
[13:18:09.458] [Server thread/CRITICAL]: Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/Menu/EditMenu" at line 64

**Comment by FoxWorn3365** [comment]
I'll fix this bug tomorrow as soon as i can and release a new version

**Comment by FoxWorn3365** [comment]
can you share the plugin's shop configuration you used?
Is located at `/path/to/your/pmmp/server/plugin_data/Shopkeepers/<YOUR NAME>.json`
Thanks :D

**Comment by gamegam** [comment]
> 사용한 플러그인의 상점 구성을 공유할 수 있습니까? 감사합니다 :D 에 있습니다`/path/to/your/pmmp/server/plugin_data/Shopkeepers/<YOUR NAME>.json`

OK

**Comment by gamegam** [comment]
> can you share the plugin's shop configuration you used? Is located at `/path/to/your/pmmp/server/plugin_data/Shopkeepers/<YOUR NAME>.json` Thanks :D


OK

**Comment by FoxWorn3365** [comment]
This should have been fixed with #4 -> https://github.com/FoxWorn3365/Shopkeepers/releases/tag/v0.9.1-pre
Awaiting confirmation

**Comment by FoxWorn3365** [comment]
No more reports, this should had be fixed with the v0.9.1a
