### ISSUE TITLE
Crash ver #dev51

### ISSUE THREAD

**Issue by BaorzK** [FoxWorn3365/Shopkeepers#18]
Error crashing version #dev51 
Link crashdump: https://www.mediafire.com/file/hka21ofcqs611dp/Wed_Jun_28-05.50.24-UTC_2023.log/file

**Comment by FoxWorn3365** [comment]
Probably your `.entities.json` folder were corrupted by a previous version, you can fix it by yourself making the object an array or you can delete the file.
If the crash will appear again write a message here
