### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by ivigb** [FoxWorn3365/Shopkeepers#19]
[12:39:54.275] [Server thread/CRITICAL]: ErrorException: "Undefined array key 1" (EXCEPTION) in "plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/Core" at line 232
--- Stack trace ---
  #0 plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/Core(232): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[21] Undefined array key 1, string[84] phar:///home/container/plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/Core, int 232)
  #1 pmsrc/src/command/PluginCommand(46): FoxWorn3365\Shopkeepers\Core->onCommand(object pocketmine\player\Player#167741, object pocketmine\command\PluginCommand#40741, string[2] sk, array[1])
  #2 pmsrc/src/command/SimpleCommandMap(212): pocketmine\command\PluginCommand->execute(object pocketmine\player\Player#167741, string[2] sk, array[1])
  #3 pmsrc/src/Server(1415): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#167741, string[9] sk create)
  #4 pmsrc/src/player/Player(1503): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#167741, string[9] sk create)
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(818): pocketmine\player\Player->chat(string[10] /sk create)
  #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#80337)
  #7 pmsrc/src/network/mcpe/NetworkSession(437): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#84899)
  #8 pmsrc/src/network/mcpe/NetworkSession(381): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#80337, string[32] M./sk create..O...f........f...D)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(217): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[81] S.../.VH.JM,Ie....{W...'g.........b3.1`o..2.o.../p..mw.]..... q.F&.u\ ....{.T.L.)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[90] ..w...h.p....U.a.M.5t..C...M..5..FYH...9..L$u.M.S].o.F:......U...4@.U.n..K..2..%)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(109): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#184239)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1674): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688474394.2832)
  #16 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #18 pmsrc/src/PocketMine(357): pocketmine\server()
  #19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[12:39:54.276] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[12:39:54.281] [Server thread/EMERGENCY]: Please upload the "/home/container/crashdumps/Tue_Jul_4-12.39.54-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[12:39:54.368] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/8914312 or use the ID #8914312.
[12:39:54.368] [Server thread/EMERGENCY]: Forcing server shutdown
[12:39:54.368] [Server thread/INFO]: Disabling Shopkeepers v0.9.1-pre

**Comment by FoxWorn3365** [comment]
🇮🇹 
L'errore è causato da una semplice mancanza di `@` alla linea quando la variabile viene definita in un if, può tranquillamente essere risolto usando correttamente il comando `/sk create <NOME>`, ad esempio `/sk create Giolleiere`

🇺🇸 
The error was cause by a missing `@` in the var definition inside the if statement.
You can simply avoid this error using the correct command `/sk create <NAME>`, for example `/sk create Food`

**Comment by ivigb** [comment]
Errore risolto!
Grazie per l'aiuto

**Comment by FoxWorn3365** [comment]
Resolved, this bug will be fixed in the next update
