### ISSUE TITLE
Crahs

### ISSUE THREAD

**Issue by Allanxa** [FoxWorn3365/Shopkeepers#32]
Thread: Main
Error: Position world is null or has been unloaded
File: pmsrc/src/world/Position
Line: 63
Type: pocketmine\utils\AssumptionFailedError
Backtrace:
#0 pmsrc/src/entity/Entity(197): pocketmine\world\Position->getWorld()
#1 plugins/Shopkeepers-main/src/FoxWorn3365/Shopkeepers/entity/Shopkeeper(33): pocketmine\entity\Entity->__construct(object pocketmine\entity\Location#106740, null)
#2 plugins/Shopkeepers-main/src/FoxWorn3365/Shopkeepers/EntityManager(130): FoxWorn3365\Shopkeepers\entity\Shopkeeper->__construct(object pocketmine\entity\Location#106740, object stdClass#106731, int 3815357194)
#3 plugins/Shopkeepers-main/src/FoxWorn3365/Shopkeepers/EntityManager(107): FoxWorn3365\Shopkeepers\EntityManager::createEntity(string[292] eyJ4IjozMjcuNTU3MiwieSI6NCwieWF3Ijo2Ni40NzA3MDMxMjUsInoiOjQzMy41NDQxLCJwaXRjaCI6, object pocketmine\Server#13)
#4 plugins/Shopkeepers-main/src/FoxWorn3365/Shopkeepers/Core(174): FoxWorn3365\Shopkeepers\EntityManager->loadPlayer(object pocketmine\player\Player#91281)

**Comment by FoxWorn3365** [comment]
Fixed in v1.3
