### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YummyLogs** [FoxWorn3365/Shopkeepers#37]
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Shopkeepers

Thread: Main
Error: Tried to schedule task to disabled scheduler
File: pmsrc/src/scheduler/TaskScheduler
Line: 86
Type: LogicException
Backtrace:
#0 pmsrc/src/scheduler/TaskScheduler(63): pocketmine\scheduler\TaskScheduler->addTask(object FoxWorn3365\Shopkeepers\pmmpStats\pmmpStatsTask#148087, int -1, int 2000)
#1 plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/Core(182): pocketmine\scheduler\TaskScheduler->scheduleRepeatingTask(object FoxWorn3365\Shopkeepers\pmmpStats\pmmpStatsTask#148087, int 2000)
#2 pmsrc/src/plugin/PluginBase(119): FoxWorn3365\Shopkeepers\Core->onEnable()
#3 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#4 pmsrc/src/Server(1389): pocketmine\plugin\PluginManager->enablePlugin(object FoxWorn3365\Shopkeepers\Core#48987)
#5 pmsrc/src/Server(1033): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#41674)
#6 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#7 pmsrc/src/PocketMine(357): pocketmine\server()
#8 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[77] 		}
[78] 	}
[79] 
[80] 	public function isQueued(TaskHandler $task) : bool{
[81] 		return $this->tasks->contains($task);
[82] 	}
[83] 
[84] 	private function addTask(Task $task, int $delay, int $period) : TaskHandler{
[85] 		if(!$this->enabled){
[86] 			throw new \LogicException("Tried to schedule task to disabled scheduler");
[87] 		}
[88] 
[89] 		if($delay <= 0){
[90] 			$delay = -1;
[91] 		}
[92] 
[93] 		if($period <= -1){
[94] 			$period = -1;
[95] 		}elseif($period < 1){
[96] 			$period = 1;

**Comment by FoxWorn3365** [comment]
Just disable the pmmpStats integration: https://github.com/FoxWorn3365/Shopkeepers#-pmmpstats-implementation
