### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by bIaBlaBla** [FoxWorn3365/Shopkeepers#38]
https://crash.pmmp.io/view/9377035

version latest

[config.txt](https://github.com/FoxWorn3365/Shopkeepers/files/12839451/config.txt)

(txt so i can upload it)
[Sat_Oct_7-23.38.56-UTC_2023.txt](https://github.com/FoxWorn3365/Shopkeepers/files/12839452/Sat_Oct_7-23.38.56-UTC_2023.txt)

HIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Shopkeepers

Thread: AsyncWorker#3
Error: Attempt to read property "status" on null
File: plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmpStats/pmmpStatsAsync
Line: 25
Type: ErrorException
Backtrace:
#0 /home/container/plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmpStats/pmmpStatsAsync(25): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[41] Attempt to read property "status" on null, string[104] phar:///home/container/plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmp, int 25)
#1 pmsrc/src/scheduler/AsyncTask(82): FoxWorn3365\Shopkeepers\pmmpStats\pmmpStatsAsync->onRun()
#2 (): pocketmine\scheduler\AsyncTask->run()

Code:
[16] 
[17]     public function onRun() : void {
[18]         // Send the http request
[19]         $ch = curl_init();
[20]         curl_setopt($ch, CURLOPT_URL, $this->url);
[21]         curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
[22]         $data = curl_exec($ch);
[23]         curl_close($ch);
[24]         $data = json_decode($data);
[25]         if ($data->status !== 200) {
[26]             var_dump("ERROR WHILE PUTTING DATA ON pmmpStats, server says: '{$data->message}'\n");
[27]         }
[28]     }
[29] }

Loaded plugins:
MCPEToDiscord 2.4.0 by JaxkDev, GamerMJay for API(s) 5.0.0
Shopkeepers 1.3.0 by FoxWorn3365 for API(s) 5.0.0
oh-my-pmmp 2.0.0-alpha by thebigcrafter for API(s) 5.0.0

uname -a: Linux 61f84316-a846-4dd7-9ec9-d3256baf70f8 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
Zend version: 4.1.23
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.11.0@0ad82ce168c82ba30d1c01ec86116ab52f589478
- daverandom/callback-validator unknown@unknown
- netresearch/jsonmapper unknown@unknown
- pocketmine/bedrock-block-upgrade-schema 3.2.0@874e1c0c9b7b620744d08b59c78354fe9f028dfa
- pocketmine/bedrock-data 2.5.0+bedrock-1.20.30@e920209393a8bf6cb15fb40c3f3149aaf8e1a2b9
- pocketmine/bedrock-item-upgrade-schema 1.5.0@3edc9ebbad9a4f2d9c8f53b3a5ba44d4a792ad93
- pocketmine/bedrock-protocol 24.0.0+bedrock-1.20.30@38a516274aa6641b0da38011af35a5587fc87895
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.19.6@93e473e20e7f4515ecf45c5ef0f9155b9247a86e
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/math 1.0.0@dc132d93595b32e9f210d78b3c8d43c662a5edbf
- pocketmine/nbt 1.0.0@20540271cb59e04672cb163dca73366f207974f1
- pocketmine/netresearch-jsonmapper v4.2.1000@078764e869e9b732f97206ec9363480a77c35532
- pocketmine/pocketmine-mp 5.6.0@338bb3fe6d70f093fc8dc01d1d3c3b4b3656fcf8
- pocketmine/raklib 0.15.1@79b7b4d1d7516dc6e322514453645ad9452b20ca
- pocketmine/raklib-ipc 0.2.0@26ed56fa9db06e4ca6e8920c0ede2e01e219bb9c
- pocketmine/snooze 0.5.0@a86d9ee60ce44755d166d3c7ba4b8b8be8360915
- ramsey/collection 2.0.0@a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5
- ramsey/uuid 4.7.4@60a4c63ab724854332900504274f6150ff26d286
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v6.3.1@edd36776956f2a6fcf577edb5b05eb0e3bdc52ae
- symfony/polyfill-ctype v1.28.0@ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb
- symfony/polyfill-mbstring v1.28.0@42292d99c55abe617799667f454222c54c60e229
HIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: Shopkeepers

Thread: AsyncWorker#3
Error: Attempt to read property "status" on null
File: plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmpStats/pmmpStatsAsync
Line: 25
Type: ErrorException
Backtrace:
#0 /home/container/plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmpStats/pmmpStatsAsync(25): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[41] Attempt to read property "status" on null, string[104] phar:///home/container/plugins/Shopkeepers.phar/src/FoxWorn3365/Shopkeepers/pmmp, int 25)
#1 pmsrc/src/scheduler/AsyncTask(82): FoxWorn3365\Shopkeepers\pmmpStats\pmmpStatsAsync->onRun()
#2 (): pocketmine\scheduler\AsyncTask->run()

Code:
[16] 
[17]     public function onRun() : void {
[18]         // Send the http request
[19]         $ch = curl_init();
[20]         curl_setopt($ch, CURLOPT_URL, $this->url);
[21]         curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
[22]         $data = curl_exec($ch);
[23]         curl_close($ch);
[24]         $data = json_decode($data);
[25]         if ($data->status !== 200) {
[26]             var_dump("ERROR WHILE PUTTING DATA ON pmmpStats, server says: '{$data->message}'\n");
[27]         }
[28]     }
[29] }

Loaded plugins:
MCPEToDiscord 2.4.0 by JaxkDev, GamerMJay for API(s) 5.0.0
Shopkeepers 1.3.0 by FoxWorn3365 for API(s) 5.0.0
oh-my-pmmp 2.0.0-alpha by thebigcrafter for API(s) 5.0.0

uname -a: Linux 61f84316-a846-4dd7-9ec9-d3256baf70f8 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
Zend version: 4.1.23
Composer libraries: 
- adhocore/json-comment 1.2.1@651023f9fe52e9efa2198cbaf6e481d1968e2377
- brick/math 0.11.0@0ad82ce168c82ba30d1c01ec86116ab52f589478
- daverandom/callback-validator unknown@unknown
- netresearch/jsonmapper unknown@unknown
- pocketmine/bedrock-block-upgrade-schema 3.2.0@874e1c0c9b7b620744d08b59c78354fe9f028dfa
- pocketmine/bedrock-data 2.5.0+bedrock-1.20.30@e920209393a8bf6cb15fb40c3f3149aaf8e1a2b9
- pocketmine/bedrock-item-upgrade-schema 1.5.0@3edc9ebbad9a4f2d9c8f53b3a5ba44d4a792ad93
- pocketmine/bedrock-protocol 24.0.0+bedrock-1.20.30@38a516274aa6641b0da38011af35a5587fc87895
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/color 0.3.1@a0421f1e9e0b0c619300fb92d593283378f6a5e1
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.19.6@93e473e20e7f4515ecf45c5ef0f9155b9247a86e
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/math 1.0.0@dc132d93595b32e9f210d78b3c8d43c662a5edbf
- pocketmine/nbt 1.0.0@20540271cb59e04672cb163dca73366f207974f1
- pocketmine/netresearch-jsonmapper v4.2.1000@078764e869e9b732f97206ec9363480a77c35532
- pocketmine/pocketmine-mp 5.6.0@338bb3fe6d70f093fc8dc01d1d3c3b4b3656fcf8
- pocketmine/raklib 0.15.1@79b7b4d1d7516dc6e322514453645ad9452b20ca
- pocketmine/raklib-ipc 0.2.0@26ed56fa9db06e4ca6e8920c0ede2e01e219bb9c
- pocketmine/snooze 0.5.0@a86d9ee60ce44755d166d3c7ba4b8b8be8360915
- ramsey/collection 2.0.0@a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5
- ramsey/uuid 4.7.4@60a4c63ab724854332900504274f6150ff26d286
- rhumsaa/uuid unknown@unknown
- symfony/filesystem v6.3.1@edd36776956f2a6fcf577edb5b05eb0e3bdc52ae
- symfony/polyfill-ctype v1.28.0@ea208ce43cbb04af6867b4fdddb1bdbf84cc28cb
- symfony/polyfill-mbstring v1.28.0@42292d99c55abe617799667f454222c54c60e229

**Comment by FoxWorn3365** [comment]
Just disable the pmmpStats integration: https://github.com/FoxWorn3365/Shopkeepers#-pmmpstats-implementation

**Comment by bIaBlaBla** [comment]
> Just disable the pmmpStats integration: https://github.com/FoxWorn3365/Shopkeepers#-pmmpstats-implementation

![image](https://github.com/FoxWorn3365/Shopkeepers/assets/147285477/454cbeda-f608-475e-aa0b-dcf7ae2d775b)
but it's nowhere to be seen

**Comment by FoxWorn3365** [comment]
You just need to add to the config a line:
```yaml
enable-pmmpstats-datashare: false
```
