### ISSUE TITLE
customitemloader

### ISSUE THREAD

**Issue by wastrr** [FoxWorn3365/Shopkeepers#5]
The items we made with the customItemLoader plugin do not appear in the trade.

**Comment by FoxWorn3365** [comment]
this bug should be fixed with the v0.9.1(https://github.com/FoxWorn3365/Shopkeepers/tree/pmmp5-dev) but i'll wait until the relase before closing the issue.
If it won't work please reply

**Comment by FoxWorn3365** [comment]
This update might have fixed the bug https://github.com/FoxWorn3365/Shopkeepers/releases/tag/v0.9.1-pre

**Comment by FoxWorn3365** [comment]
No more reports, should be had fixed with the v0.9.1a
